#
#Tue Dec 16 19:04:34 COT 2025
goog\:chromeOptions={args\=[--start-maximized, --incognito, --disable-infobars, --disable-gpu, --disable-popup-blocking, --remote-allow-origins\=*, --ignore-certificate-errors, --ignore-ssl-errors\=yes, remote-allow-origins\=*], extensions\=[]}
acceptInsecureCerts=false
browserName=chrome
