#
#Fri Feb 20 22:21:20 COT 2026
goog\:chromeOptions={args\=[--start-maximized, --incognito, --disable-infobars, --disable-gpu, --disable-popup-blocking, --remote-allow-origins\=*, --ignore-certificate-errors, --ignore-ssl-errors\=yes, remote-allow-origins\=*], extensions\=[]}
acceptInsecureCerts=false
browserName=chrome
